# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sleepy Gonzales
email: sleepygonzales123@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter: https://twitter.com/CristianVGarden
instagram: https://www.instagram.com/sleepygonzales/
facebook: https://www.facebook.com/sleepyg123/
headerbackground: https://images.unsplash.com/photo-1440227537815-f4476b789291?crop=entropy&fit=crop&fm=jpg&h=1025&ixjsv=2.1.0&ixlib=rb-0.3.5&q=80&w=1250
footerbackground: https://images.unsplash.com/photo-1440227537815-f4476b789291?crop=entropy&fit=crop&fm=jpg&h=1025&ixjsv=2.1.0&ixlib=rb-0.3.5&q=80&w=1250

# Build settings
markdown: kramdown
